/* ==============================
   Tabelas principais
   ============================== */

CREATE TABLE TIPO_RESIDUO (
  ID              NUMBER        PRIMARY KEY,
  NOME            VARCHAR2(50)  NOT NULL UNIQUE,
  DESCRICAO       VARCHAR2(150),
  PERIGOSO        NUMBER(1)     DEFAULT 0 CHECK (PERIGOSO IN (0,1))
);

CREATE TABLE PONTO_COLETA (
  ID                 NUMBER        PRIMARY KEY,
  NOME               VARCHAR2(80)  NOT NULL UNIQUE,
  LOCALIZACAO        VARCHAR2(150) NOT NULL,
  LIMITE_PESO_KG     NUMBER(10,2)  NOT NULL,
  TOTAL_RESIDUO_KG   NUMBER(10,2)  DEFAULT 0 NOT NULL,
  TOTAL_COLETADO_KG  NUMBER(10,2)  DEFAULT 0 NOT NULL
);

CREATE TABLE PONTO_DESTINO (
  ID               NUMBER        PRIMARY KEY,
  NOME             VARCHAR2(80)  NOT NULL UNIQUE,
  ENDERECO         VARCHAR2(150) NOT NULL,
  TIPO             VARCHAR2(30)  NOT NULL,
  CAPACIDADE_MAX_KG NUMBER(10,2)
);

CREATE TABLE ALERTA (
  ID              NUMBER        PRIMARY KEY,
  MENSAGEM        VARCHAR2(150) NOT NULL,
  DATA_HORA       TIMESTAMP     NOT NULL,
  PONTO_COLETA_ID NUMBER        NOT NULL
    REFERENCES PONTO_COLETA(ID)
);

CREATE TABLE COLETA (
  ID              NUMBER        PRIMARY KEY,
  DATA_AGENDADA   DATE          NOT NULL,
  DATA_REALIZADA  DATE,
  STATUS          VARCHAR2(20)  NOT NULL,
  FREQUENCIA      VARCHAR2(20)  NOT NULL,
  PONTO_COLETA_ID NUMBER        NOT NULL
    REFERENCES PONTO_COLETA(ID)
);

CREATE TABLE RESIDUO (
  ID              NUMBER        PRIMARY KEY,
  DESCRICAO       VARCHAR2(120),
  PESO_KG         NUMBER(10,2)  NOT NULL,
  DATA_DEPOSITO   DATE          NOT NULL,
  TIPO_RESIDUO_ID NUMBER        NOT NULL
    REFERENCES TIPO_RESIDUO(ID),
  PONTO_COLETA_ID NUMBER        NOT NULL
    REFERENCES PONTO_COLETA(ID),
  COLETA_ID       NUMBER
    REFERENCES COLETA(ID)
);

CREATE TABLE DESTINACAO (
  ID              NUMBER        PRIMARY KEY,
  DATA_ENVIO      DATE          NOT NULL,
  DATA_RECEBIMENTO DATE,
  PESO_KG         NUMBER(10,2) NOT NULL,
  PONTO_DESTINO_ID NUMBER       NOT NULL
    REFERENCES PONTO_DESTINO(ID)
);
