CREATE SEQUENCE SEQ_TIPO_RESIDUO      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PONTO_COLETA      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PONTO_DESTINO     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ALERTA_SEQ            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COLETA            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESIDUO_DEPOSITADO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DESTINACAO        START WITH 1 INCREMENT BY 1 NOCACHE;
